# Example config schema for SarahToolkit
version: str
plugins: dict
logging: dict
webui: dict
scheduler: dict
persistence: dict
c2: dict
evasion: dict
modules: dict
exploits: dict
delivery: dict
exfiltration: dict
p2p: dict
self_destruct: dict
twitter_c2: dict
email_c2: dict
bloodhound: dict
shodan: dict
cloud: dict
ai: dict
metasploit: dict
cobalt_strike: dict
dns_tunnel: dict
https_c2: dict
kernel_exploits: dict
zero_day: dict
supply_chain: dict
ai_weaponization: dict
sliver_c2: dict
covenant_c2: dict
container_escape: dict
steganography: dict
phishing: dict
ddos: dict
usb_infection: dict
android_payloads: dict
firmware_persistence: dict
